# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dump-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7beb6f4cffc34012b82b172ecf0546ee }}
        password: ${{ secrets.AzureAppService_ContainerPassword_badfb7f40bfa4de5a5d3905ae8c986b8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7beb6f4cffc34012b82b172ecf0546ee }}/georgespanos/dumb-ui:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dump-ui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c6b74ceb034e498c92023d286b7535fa }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7beb6f4cffc34012b82b172ecf0546ee }}/georgespanos/dumb-ui:${{ github.sha }}'